import { uniqueId } from 'lodash';
import {
  IconHome,
  IconClipboardData,
  IconLock,
  IconUser,
  IconBuildingStore,
  IconMap,
  IconSteeringWheel,
  IconPoint,
  IconReport,
  IconListCheck,
  IconDeviceDesktop,
  IconCreditCardRefund,
  IconPackage,
  IconCar,
  IconBellPlus,
  IconMail,
  IconBuildingBank,
  IconSettings,
  IconCarGarage,
  IconKey,
  IconDeviceLaptop,
  IconUsers,
  IconHeadphones,
  IconShoppingCart,
  IconPill,
  IconPizza,
  IconCarrot,
} from '@tabler/icons-react';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'Home',
  },
  {
    id: uniqueId(),
    title: 'DashBoard',
    icon: IconHome,
    href: '/dashboard',
  },
  {
    id: uniqueId(),
    title: 'Locations',
    icon: IconMap,
    href: '/locations/',
    children: [
      {
        id: uniqueId(),
        title: 'Country',
        icon: IconPoint,
        href: '/locations/country',
      },
      {
        id: uniqueId(),
        title: 'State',
        icon: IconPoint,
        href: '/locations/state',
      },
      {
        id: uniqueId(),
        title: 'City',
        icon: IconPoint,
        href: '/locations/city',
      },
      {
        id: uniqueId(),
        title: 'Zones',
        icon: IconPoint,
        href: '/locations/zones',
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   title: 'Services',
  //   icon: IconClipboardData,
  //   href: '/services/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Service Type',
  //       icon: IconPoint,
  //       href: '/services/servicetype',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Service',
  //       icon: IconPoint,
  //       href: '/services/service',
  //     },
  //   ],
  // },
  {
    id: uniqueId(),
    title: 'Services',
    icon: IconClipboardData,
    href: '/services/service',
  },
  {
    id: uniqueId(),
    title: 'Access Control',
    icon: IconLock,
    href: '/access-control/',
    children: [
      {
        id: uniqueId(),
        title: 'Department / Roles',
        icon: IconPoint,
        href: '/access-control/roles',
      },
      {
        id: uniqueId(),
        title: 'Admin User',
        icon: IconPoint,
        href: '/access-control/adminusers',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Users / Customers',
    icon: IconUser,
    href: '/Customer/',
    children: [
      {
        id: uniqueId(),
        title: 'Users / Customers',
        icon: IconPoint,
        href: '/users',
      },
      {
        id: uniqueId(),
        title: 'Blocked Users/Customers',
        icon: IconPoint,
        href: '/blocked-users',
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   title: 'Providers',
  //   icon: IconTruckDelivery,
  //   href: '/providers',
  // },
  {
    navlabel: true,
    subheader: 'On Demand Services',
  },
  {
    id: uniqueId(),
    title: 'On Demand Services',
    icon: IconPackage,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Categories',
        icon: IconPoint,
        href: '/ondemandservice/demandcategories',
      },
      {
        id: uniqueId(),
        title: 'Sub Categories',
        icon: IconPoint,
        href: '/ondemandservice/ondemandsubcategories',
      },
      {
        id: uniqueId(),
        title: 'Child Categories',
        icon: IconPoint,
        href: '/ondemandservice/ondemandchildcategories',
      },
      {
        id: uniqueId(),
        title: 'Services',
        icon: IconPoint,
        href: '/ondemandservice/ondemandservices',
      },
      {
        id: uniqueId(),
        title: 'Coupons',
        icon: IconPoint,
        href: '/ondemandservice/ondemandcoupons',
      },
      // {
      //   id: uniqueId(),
      //   title: 'Workers',
      //   icon: IconPoint,
      //   href: '/ondemandservice/ondemandworkers',
      // },
    ],
  },
  {
    id: uniqueId(),
    title: 'Service Providers List',
    icon: IconUsers,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'All Service Provider',
        icon: IconPoint,
        href: '/all-providers',
      },
      {
        id: uniqueId(),
        title: 'New Service Provider Request',
        icon: IconPoint,
        href: '/pending-service-provider',
      },
      {
        id: uniqueId(),
        title: 'Approved Service Provider',
        icon: IconPoint,
        href: '/providers',
      },
      {
        id: uniqueId(),
        title: 'Reject Service Provider',
        icon: IconPoint,
        href: '/reject-service-provider',
      },
      {
        id: uniqueId(),
        title: 'Blocked Service Provider',
        icon: IconPoint,
        href: '/blocked-service-provider',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Services Bookings',
    icon: IconPackage,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Verified Partners Bookings',
        icon: IconPoint,
        href: '/ondemandservice/verified-partners/pending',
      },
      {
        id: uniqueId(),
        title: 'Near by Shops Bookings',
        icon: IconPoint,
        href: '/ondemandservice/near-by-shops/pending',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Crm Bookings',
    icon: IconPackage,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Add Crm Booking',
        icon: IconPoint,
        href: '/add-crm-booking',
      },
      {
        id: uniqueId(),
        title: 'Crm Bookings',
        icon: IconPoint,
        href: '/ondemandservice/verified-partners-crm/pending',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Provider Complaints',
    icon: IconHeadphones,
    href: '/ondemandservice/provider-complaints',
  },
  {
    navlabel: true,
    subheader: 'ECommerce / Multivendor',
  },
  {
    id: uniqueId(),
    title: 'Grocery',
    icon: IconCarrot,
    href: '/Grocery',
    children: [
      {
        id: uniqueId(),
        title: 'Categories',
        icon: IconPoint,
        href: '/grocery-categories',
      },
      {
        id: uniqueId(),
        title: 'Sub-Categories',
        icon: IconPoint,
        href: '/grocery-subcategories',
      },
      {
        id: uniqueId(),
        title: 'Brands',
        icon: IconPoint,
        href: '/grocerys-brand',
      },
      {
        id: uniqueId(),
        title: 'Units',
        icon: IconPoint,
        href: '/grocery-units',
      },
      {
        id: uniqueId(),
        title: 'Weight',
        icon: IconPoint,
        href: '/grocerys-weight',
      },

      {
        id: uniqueId(),
        title: 'Add Grocery',
        icon: IconPoint,
        href: '/add-grocerys-Item',
      },
      {
        id: uniqueId(),
        title: 'Grocerys',
        icon: IconPoint,
        href: '/grocerys-item',
      },
      {
        id: uniqueId(),
        title: 'Grocery Orders',
        icon: IconPoint,
        href: '/grocery/pending',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Food',
    icon: IconPizza,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Categories',
        icon: IconPoint,
        href: '/food-categories',
      },
      {
        id: uniqueId(),
        title: 'Sub-Categories',
        icon: IconPoint,
        href: '/food-subcategories',
      },
      {
        id: uniqueId(),
        title: 'Cuisine Type',
        icon: IconPoint,
        href: '/cuisine-type',
      },
      {
        id: uniqueId(),
        title: 'Add Food Item',
        icon: IconPoint,
        href: '/add-food-item',
      },
      {
        id: uniqueId(),
        title: 'Food Items',
        icon: IconPoint,
        href: '/food-item',
      },
      {
        id: uniqueId(),
        title: 'Food Orders',
        icon: IconPoint,
        href: '/food/pending',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Shopping',
    icon: IconShoppingCart,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Categories',
        icon: IconPoint,
        href: '/shopping-categories',
      },
      {
        id: uniqueId(),
        title: 'Sub-Categories',
        icon: IconPoint,
        href: '/shopping-subcategories',
      },
      {
        id: uniqueId(),
        title: 'Size',
        icon: IconPoint,
        href: '/size-type',
      },
      {
        id: uniqueId(),
        title: 'Weight',
        icon: IconPoint,
        href: '/shopping-weight',
      },
      {
        id: uniqueId(),
        title: 'Color',
        icon: IconPoint,
        href: '/shopping-color',
      },
      {
        id: uniqueId(),
        title: 'Ram',
        icon: IconPoint,
        href: '/ram-type',
      },
      {
        id: uniqueId(),
        title: 'Brand',
        icon: IconPoint,
        href: '/shopping-brand',
      },
      {
        id: uniqueId(),
        title: 'Storage',
        icon: IconPoint,
        href: '/storage-type',
      },
      {
        id: uniqueId(),
        title: 'Fit Type',
        icon: IconPoint,
        href: '/fit-type',
      },
      {
        id: uniqueId(),
        title: 'Neck Type',
        icon: IconPoint,
        href: '/neck-type',
      },
      {
        id: uniqueId(),
        title: 'Material Type',
        icon: IconPoint,
        href: '/material-type',
      },
      {
        id: uniqueId(),
        title: 'Product Type',
        icon: IconPoint,
        href: '/product-types',
      },
      {
        id: uniqueId(),
        title: 'Sleeve Type',
        icon: IconPoint,
        href: '/sleeve-type',
      },
      // {
      //   id: uniqueId(),
      //   title: 'Operating System',
      //   icon: IconPoint,
      //   href: '/operating-system',
      // },
      {
        id: uniqueId(),
        title: 'Country Origin Type',
        icon: IconPoint,
        href: '/country-origin-type',
      },
      {
        id: uniqueId(),
        title: 'Add Shopping Item',
        icon: IconPoint,
        href: '/add-shopping-item',
      },
      {
        id: uniqueId(),
        title: 'Shopping Item',
        icon: IconPoint,
        href: '/shopping-item',
      },
      {
        id: uniqueId(),
        title: 'Shopping Orders',
        icon: IconPoint,
        href: '/e-commerce/pending',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Medicine',
    icon: IconPill,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Categories',
        icon: IconPoint,
        href: '/medicine-categories',
      },
      {
        id: uniqueId(),
        title: 'Sub-Categories',
        icon: IconPoint,
        href: '/medicine-subcategories',
      },
      {
        id: uniqueId(),
        title: 'Brands',
        icon: IconPoint,
        href: '/medicine-brands',
      },
      {
        id: uniqueId(),
        title: 'Units',
        icon: IconPoint,
        href: '/medicine-units',
      },
      {
        id: uniqueId(),
        title: 'Medicine Weight',
        icon: IconPoint,
        href: '/medicine-weight',
      },
      {
        id: uniqueId(),
        title: 'Medicine Form',
        icon: IconPoint,
        href: '/medicine-form',
      },
      {
        id: uniqueId(),
        title: 'Packing Types',
        icon: IconPoint,
        href: '/packing-types',
      },
      {
        id: uniqueId(),
        title: 'Therapeutic Class',
        icon: IconPoint,
        href: '/therapeutic-class',
      },
      {
        id: uniqueId(),
        title: 'Drug Categories',
        icon: IconPoint,
        href: '/drug-categories',
      },
      {
        id: uniqueId(),
        title: 'Add Medicine',
        icon: IconPoint,
        href: '/add-medicine-item',
      },
      {
        id: uniqueId(),
        title: 'Medicines',
        icon: IconPoint,
        href: '/medicine-item',
      },
      {
        id: uniqueId(),
        title: 'Medicines Orders',
        icon: IconPoint,
        href: '/medicines/pending',
      },
    ],
  },

  {
    navlabel: true,
    subheader: 'Store Management',
  },
  {
    id: uniqueId(),
    title: 'Stores',
    icon: IconBuildingStore,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Pending Stores Request',
        icon: IconPoint,
        href: '/pending-stores',
      },
      {
        id: uniqueId(),
        title: 'Stores List',
        icon: IconPoint,
        href: '/stores',
      },
      {
        id: uniqueId(),
        title: 'Blocked Stores',
        icon: IconPoint,
        href: '/blocked-stores',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Delivery Partners',
    icon: IconSteeringWheel,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Pending Request',
        icon: IconPoint,
        href: '/drivers',
      },
      {
        id: uniqueId(),
        title: 'Delivery Partners',
        icon: IconPoint,
        href: '/drivers',
      },
      {
        id: uniqueId(),
        title: 'Blocked Delivery Partners',
        icon: IconPoint,
        href: '/blocked-delivery-partners',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'ECommerce-Complaints',
    icon: IconHeadphones,
    href: '/ecommerce-complaints',
  },

  // {
  //   id: uniqueId(),
  //   title: 'ECommerce',
  //   icon: IconReport,
  //   href: '/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Categories',
  //       icon: IconPoint,
  //       href: '/categories',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Pending Categories',
  //       icon: IconPoint,
  //       href: '/pending-categories',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Sub-Categories',
  //       icon: IconPoint,
  //       href: '/sub-categories',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Pending Sub-Categories',
  //       icon: IconPoint,
  //       href: '/pending-sub-categories',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Attributes',
  //       icon: IconPoint,
  //       href: '/attributes',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Attributes Values',
  //       icon: IconPoint,
  //       href: '/attributes-values',
  //     },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Prices',
  //     //   icon: IconPoint,
  //     //   href: '/prices',
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Prices Values',
  //     //   icon: IconPoint,
  //     //   href: '/prices-values',
  //     // },
  //     {
  //       id: uniqueId(),
  //       title: 'Specifications',
  //       icon: IconPoint,
  //       href: '/specifications',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Specifications values',
  //       icon: IconPoint,
  //       href: '/specification-values',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Items',
  //       icon: IconPoint,
  //       href: '/products',
  //     },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Brands',
  //     //   icon: IconPoint,
  //     //   href: '/brands',
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Item Attributes',
  //     //   icon: IconPoint,
  //     //   href: '/itemattribute',
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Review Attributes',
  //     //   icon: IconPoint,
  //     //   href: '/reviewattributes',
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Sales Repot',
  //     //   icon: IconPoint,
  //     //   href: '/salesreport',
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Items',
  //     //   icon: IconPoint,
  //     //   href: '/items',
  //     // },
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Coupons',
  //     //   icon: IconPoint,
  //     //   href: '/coupons',
  //     // },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Stores',
  //   icon: IconBuildingStore,
  //   href: '/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Pending Stores Request',
  //       icon: IconPoint,
  //       href: '/pending-stores',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Stores List',
  //       icon: IconPoint,
  //       href: '/stores',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Blocked Stores',
  //       icon: IconPoint,
  //       href: '/blocked-stores',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Delivery Partners',
  //   icon: IconSteeringWheel,
  //   href: '/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Pending Request',
  //       icon: IconPoint,
  //       href: '/drivers',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Delivery Partners',
  //       icon: IconPoint,
  //       href: '/drivers',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Blocked Delivery Partners',
  //       icon: IconPoint,
  //       href: '/blocked-delivery-partners',
  //     },
  //   ],
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Ecommerce Orders',
  //   icon: IconListCheck,
  //   href: '/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'E-Commerce',
  //       icon: IconPoint,
  //       href: '/e-commerce/pending',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Medicines',
  //       icon: IconPoint,
  //       href: '/medicines/pending',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Grocery',
  //       icon: IconPoint,
  //       href: '/grocery/pending',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Food',
  //       icon: IconPoint,
  //       href: '/food/pending',
  //     },
  //   ],
  // },

  // {
  //   id: uniqueId(),
  //   title: 'ECommerce-Complaints',
  //   icon: IconHeadphones,
  //   href: '/ecommerce-complaints',
  // },

  // {
  //   navlabel: true,
  //   subheader: 'Parcel Services',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Parcel Service',
  //   icon: IconPackage,
  //   href: '/',
  //   children: [
  //     // {
  //     //   id: uniqueId(),
  //     //   title: 'Goods Eye',
  //     //   icon: IconPoint,
  //     //   href: '/parcelservice/parcelgoodseye',
  //     // },
  //     {
  //       id: uniqueId(),
  //       title: 'Parcel Category',
  //       icon: IconPoint,
  //       href: '/parcelservice/parcelcategory',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Parcel Weight',
  //       icon: IconPoint,
  //       href: '/parcelservice/parcelweight',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Parcel Coupons',
  //       icon: IconPoint,
  //       href: '/parcelservice/parcelcoupon',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Parcel Orders',
  //       icon: IconPoint,
  //       href: '/parcelservice/parcelorder',
  //     },
  //   ],
  // },
  // {
  //   navlabel: true,
  //   subheader: 'Cab Sevices',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Cab Sevices',
  //   icon: IconCar,
  //   href: '/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Riders',
  //       icon: IconPoint,
  //       href: '/cabservice/cab-riders',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'SOS Rides',
  //       icon: IconPoint,
  //       href: '/cabservice/cab-sos-riders',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Promo',
  //       icon: IconPoint,
  //       href: '/cabservice/cab-promo',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Complaints',
  //       icon: IconPoint,
  //       href: '/cabservice/cab-complaints',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Cab Vehicle Type',
  //       icon: IconPoint,
  //       href: '/cabservice/cab-vehicle-type',
  //     },
  //   ],
  // },
  // {
  //   navlabel: true,
  //   subheader: 'Vehicle Settings',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Vehicle Settings',
  //   icon: IconCarGarage,
  //   href: '/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Make',
  //       icon: IconPoint,
  //       href: '/vehicle/make',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Model',
  //       icon: IconPoint,
  //       href: '/vehicle/model',
  //     },
  //   ],
  // },
  // {
  //   navlabel: true,
  //   subheader: 'Rental Services',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'Rental Service',
  //   icon: IconKey,
  //   href: '/',
  //   children: [
  //     {
  //       id: uniqueId(),
  //       title: 'Rental Vehicle Type',
  //       icon: IconPoint,
  //       href: '/rentalservice/rental-vehicle-type',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Rental Type',
  //       icon: IconPoint,
  //       href: '/rentalservice/rental-type',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Rental Discount',
  //       icon: IconPoint,
  //       href: '/rentalservice/rental-discount',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Rental Orders',
  //       icon: IconPoint,
  //       href: '/rentalservice/rental-orders',
  //     },
  //     {
  //       id: uniqueId(),
  //       title: 'Rental Vehicle',
  //       icon: IconPoint,
  //       href: '/rentalservice/rental-vehicles',
  //     },
  //   ],
  // },
  {
    navlabel: true,
    subheader: 'SUBSCRIPTION SETUP',
  },
  {
    id: uniqueId(),
    title: 'Subscription Plan',
    icon: IconCreditCardRefund,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Subscription Plan',
        icon: IconPoint,
        href: '/subscriptionsplan',
      },
      {
        id: uniqueId(),
        title: 'Subscription History',
        icon: IconPoint,
        href: '/subscriptionhistory',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'Website Management',
  },
  {
    id: uniqueId(),
    title: 'Website Management',
    icon: IconDeviceLaptop,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Url Structure',
        icon: IconPoint,
        href: '/website-management/url-structure',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'General Settings',
  },
  {
    id: uniqueId(),
    title: 'Notification',
    icon: IconBellPlus,
    href: '/',
    children: [
      // OLD NOTIFICATION SYSTEM - Commented out
      // {
      //   id: uniqueId(),
      //   title: 'Send Notification',
      //   icon: IconPoint,
      //   href: '/sendnotification',
      // },
      // {
      //   id: uniqueId(),
      //   title: 'App Notification',
      //   icon: IconPoint,
      //   href: '/appnotification',
      // },

      // NEW NOTIFICATION SYSTEM - Using new API endpoints
      {
        id: uniqueId(),
        title: 'Send Notification',
        icon: IconPoint,
        href: '/notifications/send',
      },
      {
        id: uniqueId(),
        title: 'Notification History',
        icon: IconPoint,
        href: '/notifications/history',
      },
    ],
  },
  // {
  //   id: uniqueId(),
  //   title: 'On Boarding Screens',
  //   icon: IconDeviceMobile,
  //   href: '/onboardingscreens',
  // },
  {
    id: uniqueId(),
    title: 'Banner Items',
    icon: IconDeviceDesktop,
    href: '/banneritems',
  },
  // {
  //   id: uniqueId(),
  //   title: 'Email Templates',
  //   icon: IconMail,
  //   href: '/emailtemplate',
  // },
  // {
  //   id: uniqueId(),
  //   title: 'CMS Pages',
  //   icon: IconBook,
  //   href: '/cms-pages',
  // },
  {
    id: uniqueId(),
    title: 'Payments',
    icon: IconBuildingBank,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Stores Payments',
        icon: IconPoint,
        href: '/payments/store-paymensts',
      },
      {
        id: uniqueId(),
        title: 'Stores Payouts',
        icon: IconPoint,
        href: '/payments/store-payouts',
      },
      {
        id: uniqueId(),
        title: 'Drives Payments',
        icon: IconPoint,
        href: '/payments/drivers-payments',
      },
      {
        id: uniqueId(),
        title: 'Drives Payouts',
        icon: IconPoint,
        href: '/payments/drivers-payouts',
      },
      {
        id: uniqueId(),
        title: 'Providers Payments',
        icon: IconPoint,
        href: '/payments/providers-payments',
      },
      {
        id: uniqueId(),
        title: 'Providers Payouts',
        icon: IconPoint,
        href: '/payments/providers-payouts',
      },
      {
        id: uniqueId(),
        title: 'Wallet Transation',
        icon: IconPoint,
        href: '/payments/wallet-transtations',
      },
      {
        id: uniqueId(),
        title: 'PayOut Requests',
        icon: IconPoint,
        href: '/payments/payouts-request',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Website',
    icon: IconDeviceLaptop,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Home Page',
        icon: IconPoint,
        href: '/website/homepage',
      },
      {
        id: uniqueId(),
        title: 'About Us',
        icon: IconPoint,
        href: '/website/aboutus',
      },
      {
        id: uniqueId(),
        title: 'Our leadership',
        icon: IconPoint,
        href: '/website/ourvendors',
      },
      {
        id: uniqueId(),
        title: 'Testimonials',
        icon: IconPoint,
        href: '/website/testimonials',
      },
      {
        id: uniqueId(),
        title: 'Blog',
        icon: IconPoint,
        href: '/website/blog',
      },
      {
        id: uniqueId(),
        title: 'App Screens',
        icon: IconPoint,
        href: '/website/appscreens',
      },
      {
        id: uniqueId(),
        title: 'App Download Screen',
        icon: IconPoint,
        href: '/website/app-downloads-screens',
      },
      {
        id: uniqueId(),
        title: 'App Scrolling',
        icon: IconPoint,
        href: '/website/appscrolling',
      },
      {
        id: uniqueId(),
        title: 'Announcements',
        icon: IconPoint,
        href: '/website/Announcements',
      },
      {
        id: uniqueId(),
        title: 'Accept Payments',
        icon: IconPoint,
        href: '/website/accept-payments',
      },
      {
        id: uniqueId(),
        title: 'Website All Headings',
        icon: IconPoint,
        href: '/website/all-modules',
      },
      {
        id: uniqueId(),
        title: 'Enquiry',
        icon: IconPoint,
        href: '/website/enquiry',
      },
    ],
  },

  //website latest 

  // {
  //   id: uniqueId(),
  //   title: 'Website',
  //   icon: IconDeviceLaptop,
  //   href: '/',
  //   children: [

  //     {
  //       id: uniqueId(),
  //       title: 'Testimonials',
  //       icon: IconPoint,
  //       href: '/website/testimonialslatest',
  //     },

  //   ],
  // },


  // download a

  {
    id: uniqueId(),
    title: 'Settings',
    icon: IconSettings,
    href: '/',
    children: [
      {
        id: uniqueId(),
        title: 'Global Settings',
        icon: IconPoint,
        href: '/globalsettings',
      },
      {
        id: uniqueId(),
        title: 'App Settings',
        icon: IconPoint,
        href: '/appSettings',
      },
      // {
      //   id: uniqueId(),
      //   title: 'Bussiness Model Setting',
      //   icon: IconPoint,
      //   href: '/bussinessmodelsettings',
      // },
      // {
      //   id: uniqueId(),
      //   title: 'App Banners',
      //   icon: IconPoint,
      //   href: '/appbanners',
      // },
      // {
      //   id: uniqueId(),
      //   title: 'Currencies',
      //   icon: IconPoint,
      //   href: '/currencies',
      // },
      // {
      //   id: uniqueId(),
      //   title: 'Payment Method',
      //   icon: IconPoint,
      //   href: '/paymentmethod',
      // },
      {
        id: uniqueId(),
        title: 'Radius Configuration',
        icon: IconPoint,
        href: '/radiusconfiguration',
      },
      {
        id: uniqueId(),
        title: 'Tax Setting',
        icon: IconPoint,
        href: '/taxsettings',
      },
      {
        id: uniqueId(),
        title: 'Delivery Charges',
        icon: IconPoint,
        href: '/deliverycharges',
      },
      {
        id: uniqueId(),
        title: 'Refund Policy',
        icon: IconPoint,
        href: '/refund-policy',
      },
      {
        id: uniqueId(),
        title: 'Terms & Conditions',
        icon: IconPoint,
        href: '/terms',
      },
      {
        id: uniqueId(),
        title: 'Privacy Policy',
        icon: IconPoint,
        href: '/privacypolicy',
      },
      {
        id: uniqueId(),
        title: 'Faqs',
        icon: IconPoint,
        href: '/faqs',
      },
    ],
  },
];

export default Menuitems;
