import { uniqueId } from 'lodash';
import {
  IconHome,
  IconClipboardData,
  IconMap,
  IconUser,
  IconPoint,
  IconDeviceDesktop,
  IconCreditCardRefund,
  IconPackage,
  IconBellPlus,
  IconBuildingBank,
  IconSettings,
  IconDeviceLaptop,
  IconUsers,
  IconHeadphones,
  IconUserPlus,
  IconBriefcase,
  IconBook,
} from '@tabler/icons-react';

const Menuitems = [
  {
    navlabel: true,
    subheader: 'CORE CONTROL',
    permission: 'dashboard_view',
  },
  {
    id: uniqueId(),
    title: 'DashBoard',
    icon: IconHome,
    href: '/dashboard',
    permission: 'dashboard_view',
  },
  {
    id: uniqueId(),
    title: 'Locations',
    icon: IconMap,
    href: '/locations/',
    permission: 'locations_view',
    children: [
      {
        id: uniqueId(),
        title: 'Country',
        icon: IconPoint,
        href: '/locations/country',
        permission: 'country_view',
      },
      {
        id: uniqueId(),
        title: 'State',
        icon: IconPoint,
        href: '/locations/state',
        permission: 'state_view',
      },
      {
        id: uniqueId(),
        title: 'City',
        icon: IconPoint,
        href: '/locations/city',
        permission: 'city_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Business Verticals',
    icon: IconClipboardData,
    href: '/business-verticals/',
    permission: 'services_view',
    children: [
      {
        id: uniqueId(),
        title: 'Services',
        icon: IconPoint,
        href: '/services/service',
        permission: 'services_view',
      },
      {
        id: uniqueId(),
        title: 'Knowledge Base',
        icon: IconBook,
        href: '/knowledge-base',
        permission: 'services_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Users / Customers',
    icon: IconUser,
    href: '/Users/',
    permission: 'users_customers_view',
    children: [
      {
        id: uniqueId(),
        title: 'Users / Customers',
        icon: IconPoint,
        href: '/users',
        permission: 'users_view',
      },
      {
        id: uniqueId(),
        title: 'Blocked Users/Customers',
        icon: IconPoint,
        href: '/blocked-users',
        permission: 'blocked_users_view',
      },
      {
        id: uniqueId(),
        title: 'Delete Users/Customers',
        icon: IconPoint,
        href: '/delete-users',
        permission: 'delete_users_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Advertisements',
    icon: IconPackage,
    href: '/advertisements',
    permission: 'banner_image_view',
    children: [
      {
        id: uniqueId(),
        title: 'Coupons',
        icon: IconPoint,
        href: '/advertisments/offers',
        permission: 'banner_image_view',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'BOOKINGS',
    permission: 'bookings_view',
  },
  {
    id: uniqueId(),
    title: 'Bookings',
    icon: IconClipboardData,
    href: '',
    permission: 'bookings_view',
    children: [
      {
        id: uniqueId(),
        title: 'Dashboard',
        icon: IconPoint,
        href: '/bookings/dashboard',
        permission: 'bookings_dashboard_view',
      },
      {
        id: uniqueId(),
        title: 'Book service via CRM',
        icon: IconPoint,
        href: '/add-crm-booking',
        permission: 'add_crm_view',
      },
      {
        id: uniqueId(),
        title: 'Verified Partner Orders',
        icon: IconPoint,
        href: '/bookings/verified-partner',
        permission: 'verified_partner_orders_view',
      },
      {
        id: uniqueId(),
        title: 'Service Center Orders',
        icon: IconPoint,
        href: '/bookings/service-center',
        permission: 'professional_orders_view',
      },
      {
        id: uniqueId(),
        title: 'Professional Services',
        icon: IconPoint,
        href: '/bookings/professional',
        permission: 'professional_orders_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Instant Bookings \n Website',
    icon: IconDeviceDesktop,
    href: '/bookings/',
    permission: 'add_crm_view',
    children: [
      {
        id: uniqueId(),
        title: 'Bookings',
        icon: IconPoint,
        href: '/bookings/crm-website',
        permission: 'add_crm_view',
      },
      {
        id: uniqueId(),
        title: 'categories by cities',
        icon: IconPoint,
        href: '/bookings/website-city-management',
        permission: 'add_crm_view',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'D-Hub Services',
    permission: 'on_demand_services_view',
  },
  {
    id: uniqueId(),
    title: 'On Demand Services',
    icon: IconPackage,
    href: '/On Demand Services/',
    permission: 'on_demand_services_view',
    children: [
      {
        id: uniqueId(),
        title: 'Categories',
        icon: IconPoint,
        href: '/ondemandservice/demandcategories',
        permission: 'on_demand_categories_view',
      },
      {
        id: uniqueId(),
        title: 'Sub Categories',
        icon: IconPoint,
        href: '/ondemandservice/ondemandsubcategories',
        permission: 'on_demand_sub_categories_view',
      },
      {
        id: uniqueId(),
        title: 'Child Categories',
        icon: IconPoint,
        href: '/ondemandservice/ondemandchildcategories',
        permission: 'on_demand_child_categories_view',
      },
      {
        id: uniqueId(),
        title: 'Services',
        icon: IconPoint,
        href: '/ondemandservice/ondemandservices',
        permission: 'on_demand_service_view',
      }
      //,
      // {
      //   id: uniqueId(),
      //   title: 'Coupons',
      //   icon: IconPoint,
      //   href: '/ondemandservice/ondemandcoupons',
      //   permission: 'on_demand_coupons_view',
      // },
    ],
  },
  {
    id: uniqueId(),
    title: 'Service Providers List',
    icon: IconUsers,
    href: '/ServiceProvidersList',
    permission: 'service_providers_view',
    children: [
      {
        id: uniqueId(),
        title: 'All Service Provider',
        icon: IconPoint,
        href: '/all-providers',
        permission: 'all_providers_view',
      },
      {
        id: uniqueId(),
        title: 'New Service Provider Request',
        icon: IconPoint,
        href: '/pending-service-provider',
        permission: 'new_providers_view',
      },
      {
        id: uniqueId(),
        title: 'Approved Service Provider',
        icon: IconPoint,
        href: '/providers',
        permission: 'approved_providers_view',
      },
      {
        id: uniqueId(),
        title: 'Reject Service Provider',
        icon: IconPoint,
        href: '/reject-service-provider',
        permission: 'rejected_providers_view',
      },
      {
        id: uniqueId(),
        title: 'Blocked Service Provider',
        icon: IconPoint,
        href: '/blocked-service-provider',
        permission: 'blocked_providers_view',
      },
      {
        id: uniqueId(),
        title: 'Deleted Service Provider',
        icon: IconPoint,
        href: '/deleted-service-provider',
        permission: 'blocked_providers_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Professional Services',
    icon: IconUser,
    href: '/professional-categories',
    permission: 'Near_by_professionals',
    children: [
      {
        id: uniqueId(),
        title: 'Categories',
        icon: IconPoint,
        href: '/professional-categories',
        permission: 'Near_by_professionals',
      },
      {
        id: uniqueId(),
        title: 'SubCategories',
        icon: IconPoint,
        href: '/professional-subcategories',
        permission: 'Near_by_professionals',
      },
      {
        id: uniqueId(),
        title: 'All profesionals',
        icon: IconPoint,
        href: '/AllprofessionalProviders',
        permission: 'Near_by_professionals',
      },
      {
        id: uniqueId(),
        title: 'New Professional Requests',
        icon: IconPoint,
        href: '/pendingprofessionalserviceproviderrequest',
        permission: 'Near_by_professionals',
      },
      {
        id: uniqueId(),
        title: 'Rejected professionals',
        icon: IconPoint,
        href: '/rejectedProfessionalProvider',
        permission: 'Near_by_professionals',
      },
      {
        id: uniqueId(),
        title: 'Blocked professionals',
        icon: IconPoint,
        href: '/BlockedProfessionalProvider',
        permission: 'Near_by_professionals',
      },
      {
        id: uniqueId(),
        title: 'Deleted professionals',
        icon: IconPoint,
        href: '/DeletedProfessionalProvider',
        permission: 'Near_by_professionals',
      },
      {
        id: uniqueId(),
        title: 'Amenities',
        icon: IconPoint,
        href: '/amenities',
        permission: 'Near_by_professionals',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'Platform Management',
  },
  {
    id: uniqueId(),
    title: 'Careers',
    icon: IconBriefcase,
    href: '/careers',
    children: [
      {
        id: uniqueId(),
        title: 'Job Roles',
        icon: IconPoint,
        href: '/careers/roles',
      },
      {
        id: uniqueId(),
        title: 'Job Postings',
        icon: IconPoint,
        href: '/careers/jobs',
      },
      {
        id: uniqueId(),
        title: 'Applications',
        icon: IconPoint,
        href: '/careers/applications',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Subscription Plan',
    icon: IconCreditCardRefund,
    href: '/SubscriptionPlan',
    permission: 'subscription_plan_view',
    children: [
      {
        id: uniqueId(),
        title: 'Subscription Plan',
        icon: IconPoint,
        href: '/subscriptionsplan',
        permission: 'subscription_plan_view',
      },
      {
        id: uniqueId(),
        title: 'Subscription History',
        icon: IconPoint,
        href: '/subscriptionhistory',
        permission: 'subscription_history_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Website Management',
    icon: IconDeviceLaptop,
    href: '/website-management',
    children: [
      {
        id: uniqueId(),
        title: 'Url Structure',
        icon: IconPoint,
        href: '/website-management/url-structure',
      },
      {
        id: uniqueId(),
        title: 'Manage Website Screens',
        icon: IconPoint,
        href: '/website-management/manage-screens',
      },
      {
        id: uniqueId(),
        title: 'About Us',
        icon: IconPoint,
        href: '/website-management/about-us',
      },
      {
        id: uniqueId(),
        title: 'Header Management',
        icon: IconPoint,
        href: '/website-management/navbar-management',
      },
      {
        id: uniqueId(),
        title: 'SEO Management',
        icon: IconPoint,
        href: '/website-management/seo-management',
      },
      {
        id: uniqueId(),
        title: 'Spa & Salons Hero',
        icon: IconPoint,
        href: '/website-management/spa-hero',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Support Management',
    icon: IconHeadphones,
    href: '/support-management',
    children: [
      {
        id: uniqueId(),
        title: 'Dashboard',
        icon: IconPoint,
        href: '/support-management/dashboard',
      },
      {
        id: uniqueId(),
        title: 'Manage Tickets',
        icon: IconPoint,
        href: '/ondemandservice/provider-complaints',
      },
      {
        id: uniqueId(),
        title: 'Enquiries',
        icon: IconPoint,
        href: '/support-management/website-leads',
        permission: 'add_crm_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Referral Management',
    icon: IconUserPlus,
    href: '/referrals/dashboard',
    children: [
      {
        id: uniqueId(),
        title: 'Referral Dashboard',
        icon: IconPoint,
        href: '/referrals/dashboard',
      },
      {
        id: uniqueId(),
        title: 'Referral Tracking',
        icon: IconPoint,
        href: '/referrals/tracking',
      },
      {
        id: uniqueId(),
        title: 'Referral Settings',
        icon: IconPoint,
        href: '/referrals/settings',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Payment Management',
    icon: IconBuildingBank,
    href: '/Payments',
    permission: 'payments_view',
    children: [
      {
        id: uniqueId(),
        title: 'Overview',
        icon: IconPoint,
        href: '/payments/overview',
        permission: 'payments_view',
      },
      {
        id: uniqueId(),
        title: 'Booking Payments',
        icon: IconPoint,
        href: '/payments/booking-payments',
        permission: 'providers_payments_view',
      },
      {
        id: uniqueId(),
        title: 'Wallet',
        icon: IconPoint,
        href: '/payments/wallet-ledger',
        permission: 'wallet_transaction_view',
      },
      {
        id: uniqueId(),
        title: 'Admin Wallet',
        icon: IconPoint,
        href: '/payments/admin-wallet',
        permission: 'payments_view',
      },
      {
        id: uniqueId(),
        title: 'Withdrawals',
        icon: IconPoint,
        href: '/payments/withdrawals',
        permission: 'payout_requests_view',
      },
      {
        id: uniqueId(),
        title: 'Subscriptions',
        icon: IconPoint,
        href: '/payments/subscriptions',
        permission: 'subscription_history_view',
      },
    ],
  },
  {
    navlabel: true,
    subheader: 'General Settings',
    permission: 'notification_view',
  },
  {
    id: uniqueId(),
    title: 'Notification',
    icon: IconBellPlus,
    href: '/Notification',
    permission: 'notification_view',
    children: [
      {
        id: uniqueId(),
        title: 'Send Notification',
        icon: IconPoint,
        href: '/notifications/send',
        permission: 'app_notification_view',
      },
      {
        id: uniqueId(),
        title: 'Notification History',
        icon: IconPoint,
        href: '/notifications/history',
        permission: 'app_notification_view',
      },
    ],
  },
  {
    id: uniqueId(),
    title: 'Settings',
    icon: IconSettings,
    href: '/Settings',
    permission: 'settings_view',
    children: [
      {
        id: uniqueId(),
        title: 'Global Settings',
        icon: IconPoint,
        href: '/globalsettings',
        permission: 'global_settings_view',
      },
      {
        id: uniqueId(),
        title: 'Tax Setting',
        icon: IconPoint,
        href: '/taxsettings',
        permission: 'tax_setting_view',
      },
      {
        id: uniqueId(),
        title: 'Commission Settings',
        icon: IconPoint,
        href: '/servicebookingcharges',
        permission: 'Service_booking_charges',
      },
      {
        id: uniqueId(),
        title: 'Policies Management',
        icon: IconPoint,
        href: '/policies-management/applications',
        permission: 'settings_view',
        children: [
          {
            id: uniqueId(),
            title: 'Applications',
            icon: IconPoint,
            href: '/policies-management/applications',
            permission: 'settings_view',
          },
          {
            id: uniqueId(),
            title: 'Privacy & Terms',
            icon: IconPoint,
            href: '/policies-management/privacy-terms',
            permission: 'settings_view',
          },
          {
            id: uniqueId(),
            title: 'FAQs',
            icon: IconPoint,
            href: '/policies-management/faqs',
            permission: 'settings_view',
          },
          {
            id: uniqueId(),
            title: 'Refund Policy',
            icon: IconPoint,
            href: '/policies-management/refund-policy',
            permission: 'settings_view',
          },
        ],
      },
    ],
  },
];

export default Menuitems;
